#!/bin/bash

BENCHMARK_DIR=Benchmark
INPUT_DIR=$BENCHMARK_DIR/Inputs
OUTPUT_DIR=$BENCHMARK_DIR/Outputs

NBODY_BINARY=$1
NBODY_BINARY_NAME=$(basename $NBODY_BINARY)
GEN_BINARY=$(dirname $NBODY_BINARY)/gen

DT=0.01f
STEPS=1000
THREADS_PER_BLOCK=512
WRITE_INTENSITY=10
RED_THREADS=4096
RED_THREADS_PER_BLOCK=128

OUTPUT_FILE=$OUTPUT_DIR/

mkdir -p $BENCHMARK_DIR
mkdir -p $INPUT_DIR
mkdir -p $OUTPUT_DIR

N=$((20 * 4096))

INPUT=$INPUT_DIR/Input$N.h5
OUTPUT=$OUTPUT_DIR/${NBODY_BINARY_NAME}Output${N}.h5

if [ ! -f $INPUT ]; then
  $GEN_BINARY $N $INPUT >> /dev/null
fi


# sudo /opt/nvidia/nsight-compute/2024.3.1//ncu --set full --launch-count 1 -o prof-2 -f "$NBODY_BINARY" $N $DT $STEPS $THREADS_PER_BLOCK $WRITE_INTENSITY $RED_THREADS "$RED_THREADS_PER_BLOCK" $INPUT "$OUTPUT"
ncu --verbose --set full --launch-count 1 -o prof-2 -f "$NBODY_BINARY" $N $DT $STEPS $THREADS_PER_BLOCK $WRITE_INTENSITY $RED_THREADS "$RED_THREADS_PER_BLOCK" $INPUT "$OUTPUT"