
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/apps/all/CMake/3.27.6-GCCcore-13.2.0/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:20 (project)"
    message: |
      The system is: Linux - 4.18.0-513.24.1.el8_9.x86_64 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/apps/all/CMake/3.27.6-GCCcore-13.2.0/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/apps/all/CMake/3.27.6-GCCcore-13.2.0/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/apps/all/CMake/3.27.6-GCCcore-13.2.0/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:20 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /apps/all/GCCcore/13.2.0/bin/gcc 
      Build flags: -O3;-fPIC;-march=znver2
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/xkrato61/pcg/pcg-proj1/CMakeFiles/3.27.6/CompilerIdC/a.out
      
